sudo: required
services:
- docker
language: bash
os: linux
arch: amd64          
os: linux     
dist: focal 

script:
# build image
- docker build -t andrevs/knxd .
# push image
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker tag andrevs/knxd andrevs/knxd:amd64
- docker push andrevs/knxd:amd64
