#!/bin/sh

SERVICE="$1"

# TODO make this a ENV requirement
RESULT=`knxtool groupread ip:localhost 0/0/10`

if [ "${RESULT}" = "Send request" ]; then
    echo "knxd healthcheck OK"
    exit 0
fi
echo "knx healthcheck ERROR"
exit 1
